services:
  mongo:
    image: mongo:latest
    networks:
      - dbdata
    env_file: .docker.env
    restart: always

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./.nginx/default_https.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
    environment:
      - TZ=Europe/Rome
    networks:
      - default
    depends_on:
      - password-manager
    restart: always
##    secrets:
##      - cert
##      - key

  password-manager:
    build: .
    networks:
      - default
      - dbdata
    env_file: .docker.env
    restart: always
##    secrets:
##      - cert
##      - key

networks:
  dbdata:
    driver: bridge
  
  default:
    name: webapp

##secrets:
##  cert:
##    file: ./.nginx/.certs/pw-managerRootCA.crt
##  key:
##    file: ./.nginx/.certs/rootCA.key
