services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - dbdata
    env_file: .mongo.env

  nginx:
    image: nginx:latest
    container_name: nginx-webapp
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/rootCA.crt:/etc/ssl/certs/rootCA.crt
      - ./.nginx/rootCA.key:/etc/ssl/certs/rootCA.key
    ports:
      - "443:443"
    networks:
      - default
    depends_on:
      - password-manager
    environment:
      - TZ=Europe/Rome

  password-manager:
    build: .
    networks:
      - default
      - dbdata
    restart: on-failure
    environment:
      - TZ=Europe/Rome

networks:
  dbdata:
    driver: bridge
  
  default:
    name: webapp
