-- CREATE TABLE FOR THE USER CREDENTIALS AND LOGIN. CREATE TABLE FOR THE PASSWORD'S USER

DROP TABLE IF EXISTS "User";
SELECT 'IF OBJECT_ID(''' +TABLE_NAME + ''') IS NOT NULL BEGIN DROP TABLE [' + TABLE_NAME + '] END;' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '[Password]%';

CREATE TABLE "User" ("id" INTEGER PRIMARY KEY NOT NULL, "username" TEXT NOT NULL, "email" TEXT, "password" TEXT NOT NULL);