-- CREATE TABLE FOR THE USER CREDENTIALS AND LOGIN. CREATE TABLE FOR THE PASSWORD'S USER

DROP TABLE IF EXISTS "User"; 
-- SELECT 'IF OBJECT_ID(''' + TABLE_NAME + ''') IS NOT NULL BEGIN DROP TABLE [' + TABLE_NAME + '] END;' FROM sqlite_master WHERE type='table' AND TABLE_NAME LIKE '[Password]%'; 
DROP TABLE IF EXISTS (SELECT name FROM sqlite_master WHERE type='table' ORDER BY name);


CREATE TABLE "User" ("id" INTEGER PRIMARY KEY NOT NULL, "username" TEXT NOT NULL, "email" TEXT, "password" TEXT NOT NULL); 