-- CREATE TABLE FOR THE USER CREDENTIALS AND LOGIN. CREATE TABLE FOR THE PASSWORD'S USER

DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Password";
CREATE TABLE "User" ("id" INTEGER PRIMARY KEY NOT NULL, "username" TEXT NOT NULL, "email" TEXT, "password" TEXT NOT NULL);
CREATE TABLE "Password" ("id" INTEGER PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "username" TEXT NOT NULL, "password" TEXT NOT NULL, "uri" TEXT NOT NULL, "id_user" INTEGER NOT NULL, FOREIGN KEY ("id_user") REFERENCES User("id"));